var modules =
[
    [ "ADC: 12-bit SAR Analog-to-Digital Converter Driver", "group__lpc__adc.html", "group__lpc__adc" ],
    [ "AES: AES encryption decryption driver", "group__aes.html", "group__aes" ],
    [ "CMP: Comparator driver", "group__jn__cmp.html", "group__jn__cmp" ],
    [ "CTIMER: Standard counter/timers", "group__ctimer.html", "group__ctimer" ],
    [ "Clock: Clock driver", "group__clock.html", "group__clock" ],
    [ "Common Driver", "group__ksdk__common.html", "group__ksdk__common" ],
    [ "DMA: Direct Memory Access Controller Driver", "group__dma.html", "group__dma" ],
    [ "DMIC: Digital Microphone", "group__dmic.html", "group__dmic" ],
    [ "Debug Console", "group__debugconsole.html", "group__debugconsole" ],
    [ "FLASH: Flash driver", "group__jn__flash.html", "group__jn__flash" ],
    [ "FLASHIAP: Flash In Application Programming Driver", "group__flashiap__driver.html", "group__flashiap__driver" ],
    [ "FLEXCOMM: FLEXCOMM Driver", "group__flexcomm.html", "group__flexcomm" ],
    [ "FMEAS: Frequency Measure Driver", "group__fmeas.html", "group__fmeas" ],
    [ "GINT: Group GPIO Input Interrupt Driver", "group__gint__driver.html", "group__gint__driver" ],
    [ "GPIO: General Purpose I/O", "group__lpc__gpio.html", "group__lpc__gpio" ],
    [ "GenericList", "group__GenericList.html", "group__GenericList" ],
    [ "I2C: Inter-Integrated Circuit Driver", "group__i2c.html", "group__i2c" ],
    [ "INPUTMUX: Input Multiplexing Driver", "group__inputmux__driver.html", "group__inputmux__driver" ],
    [ "IOCON: I/O pin configuration", "group__jn__iocon.html", "group__jn__iocon" ],
    [ "IRM: Infra-Red Modulator driver", "group__jn__cic__irb.html", "group__jn__cic__irb" ],
    [ "NTAG: integrated NTAG", "group__jn__ntag.html", "group__jn__ntag" ],
    [ "PINT: Pin Interrupt and Pattern Match Driver", "group__pint__driver.html", "group__pint__driver" ],
    [ "PWM: Pulse Width Modulator", "group__pwm__driver.html", "group__pwm__driver" ],
    [ "Power: Power driver", "group__power.html", "group__power" ],
    [ "RNG: Random Number generator", "group__jn__rng.html", "group__jn__rng" ],
    [ "ROM_API", "group__ROM__API.html", "group__ROM__API" ],
    [ "RTC: Real Time Clock", "group__rtc.html", "group__rtc" ],
    [ "SHA: SHA encryption decryption driver", "group__sha.html", "group__sha" ],
    [ "SPI: Serial Peripheral Interface Driver", "group__spi.html", "group__spi" ],
    [ "SPIFI: SPIFI flash interface driver", "group__spifi.html", "group__spifi" ],
    [ "Serial Manager", "group__serialmanager.html", "group__serialmanager" ],
    [ "UART_Adapter", "group__UART__Adapter.html", "group__UART__Adapter" ],
    [ "USART: Universal Asynchronous Receiver/Transmitter Driver", "group__usart.html", "group__usart" ],
    [ "WWDT: Windowed Watchdog Timer Driver", "group__wwdt.html", "group__wwdt" ],
    [ "Wtimer", "group__wtimer.html", "group__wtimer" ]
];